apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elastiflow-elasticsearch-oss
  name: elastiflow-elasticsearch-oss
spec:
  containers:
  - env:
    - name: ES_JAVA_OPTS
      value: -Xms2g -Xmx2g
    - name: action.destructive_requires_name
      value: "true"
    - name: bootstrap.memory_lock
      value: "true"
    - name: cluster.name
      value: elastiflow
    - name: http.port
      value: "9200"
    - name: network.host
      value: 0.0.0.0
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    name: elastiflow-elasticsearch-oss
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elastiflow-elasticsearch-oss-claim0
  restartPolicy: Never
  volumes:
  - name: elastiflow-elasticsearch-oss-claim0
    persistentVolumeClaim:
      claimName: elastiflow-elasticsearch-oss-claim0
status: {}
