apiVersion: v1
kind: Service
metadata:
  name: {{ template "elastiflow.fullname" . }}-kibana
  labels:
    app: {{ template "elastiflow.name" . }}
    chart: {{ template "elastiflow.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:  
  - name: "URL"
    port: 9200
    targetPort: 9200
  selector:
    app: {{ template "elastiflow.name" . }}
    instance: {{ .Values.Instance }}
    component: elasticsearch
status:
  loadBalancer: {}