apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "elastiflow.fullname" . }}-elasticsearch-oss-claim0
  labels:
    app: {{ template "elastiflow.name" . }}
    chart: {{ .Release.Name }}
    release: {{ .Values.Instance }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
