apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "elastiflow.fullname" . }}-elasticsearch-oss
  labels:
    app: {{ template "elastiflow.name" . }}
    chart: {{ .Release.Name }}
    release: {{ .Values.Instance }}
    component: elasticsearch  
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "elastiflow.name" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.0.1
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: {{ template "elastiflow.fullname" . }}-elasticsearch-oss-claim0
      volumes:
      - name: {{ template "elastiflow.fullname" . }}-elasticsearch-oss-claim0
        persistentVolumeClaim:
          claimName: {{ template "elastiflow.fullname" . }}-elasticsearch-oss-claim0