apiVersion: v1
kind: Service
metadata:
  name: {{ template "elastiflow.fullname" . }}-elastiflow
  labels:
    app: {{ template "elastiflow.name" . }}
    chart: {{ template "elastiflow.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:  
  - name: "ipfix"
    port: 4739
    targetPort: 4739
  - name: "netflow"
    port: 2055
    targetPort: 2055
  - name: "sflow"
    port: 6343
    targetPort: 6343
  selector:
    app: {{ template "elastiflow.name" . }}
    instance: {{ .Values.Instance }}
    component: elastiflow
status:
  loadBalancer: {}