apiVersion: v1
kind: Service
metadata:
  name: {{ template "elastiflow.fullname" . }}-kibana
  labels:
    app: {{ template "elastiflow.name" . }}
    chart: {{ template "elastiflow.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:  
  - name: "url"
    port: 9200
    targetPort: 9200
  - name: "server-port"
    port: 5601
    targetPort: 5601
  selector:
    app: {{ template "elastiflow.name" . }}
    instance: {{ .Values.Instance }}
    component: kibana
status:
  loadBalancer: {}